window.onload = main;
function main(){
    document.title = "Woowoo's plugins";
    var elements = document.getElementsByTagName("p");
    for(i = 0; i < elements.length; i++){
        a = elements[i];
        a.innerHTML = "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et condimentum ante, eu suscipit tortor. Phasellus ornare velit at augue dictum, eu mattis dui rutrum. Curabitur ultricies elit eget augue auctor maximus. In tellus urna, semper eu turpis porttitor, sagittis facilisis metus. Mauris nisi dui, mattis at sodales vel, sagittis a risus. Mauris pellentesque lectus elit, et semper purus rutrum ac. Aliquam maximus nunc at dolor imperdiet ultricies. Nunc aliquet mattis purus id tristique. Aliquam maximus eros vel tempor rutrum."
        +"Proin ultrices sem tellus, non facilisis purus congue sit amet. Suspendisse venenatis orci at enim dictum commodo. Curabitur placerat tincidunt lacus, et semper ipsum sagittis ac. Duis id enim accumsan, condimentum erat et, auctor nunc. Etiam orci nisl, viverra at purus vulputate, fermentum efficitur massa. Nunc urna quam, porta porta bibendum id, aliquam nec magna. Aenean lobortis ipsum porttitor lacus ullamcorper ornare. Suspendisse justo diam, ultricies eu sem non, porttitor venenatis turpis."
        +"Cras vulputate, tellus ac facilisis sagittis, ligula felis consequat neque, sed pharetra purus dui ac felis. Fusce sed tortor sapien. Morbi sem nisl, sagittis ut ante quis, maximus placerat neque. Donec nec eleifend nunc, in consequat ex. Nunc commodo leo malesuada mi faucibus, sodales maximus lorem tincidunt. Nulla non mollis magna. Sed eu massa vel orci sollicitudin tempor quis nec tellus. Quisque id ullamcorper sem. Aenean eu felis non leo lobortis hendrerit. Integer volutpat feugiat lacus. Sed tempor, leo suscipit varius fringilla, dui sem convallis lorem, non elementum lacus ex sed odio. Aenean at quam lobortis, ullamcorper enim a, posuere turpis. Sed bibendum lacus vel magna mollis, nec rutrum erat aliquet."
        +"Praesent in magna dolor. Suspendisse sed ultricies orci, id porta mi. Pellentesque varius, nibh in gravida sagittis, turpis justo congue dolor, nec pellentesque lectus orci vel odio. Donec tortor justo, tempus in metus nec, ullamcorper tempor erat. Suspendisse aliquet sed sapien nec sagittis. Duis ut efficitur mauris, vel cursus libero. Maecenas et luctus dolor, et condimentum urna. Phasellus sit amet orci pretium, consectetur tortor ut, tempus lorem. Mauris vel dolor massa. Nulla lobortis, sapien a rhoncus sodales, nisi diam vulputate mi, id vehicula mauris sem sit amet massa. Cras fermentum, nibh sed rutrum mattis, turpis erat commodo sem, nec molestie felis ligula at sapien. Quisque pellentesque at nisl vitae blandit. Nulla facilisi."
        +"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas efficitur vel est quis cursus. Aenean lacinia tortor lobortis eros interdum, quis gravida nisi semper. Cras mauris nisi, blandit sit amet magna eget, porta ultricies sapien. Nunc ante nibh, semper sed nunc sit amet, congue eleifend augue. Sed hendrerit quis sem a dignissim. Duis sed est venenatis, laoreet odio at, aliquet nibh. Cras neque nibh, porttitor in feugiat posuere, tempus a leo. Cras gravida commodo orci, a interdum sapien dictum at. Maecenas porttitor ex non nibh porttitor, vel fringilla augue interdum. Duis sit amet justo diam. Praesent malesuada commodo imperdiet. Nam at nulla rutrum, ornare tellus vitae, accumsan tortor. Sed pharetra justo sit amet bibendum volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos."
        +"Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nam et condimentum ante, eu suscipit tortor. Phasellus ornare velit at augue dictum, eu mattis dui rutrum. Curabitur ultricies elit eget augue auctor maximus. In tellus urna, semper eu turpis porttitor, sagittis facilisis metus. Mauris nisi dui, mattis at sodales vel, sagittis a risus. Mauris pellentesque lectus elit, et semper purus rutrum ac. Aliquam maximus nunc at dolor imperdiet ultricies. Nunc aliquet mattis purus id tristique. Aliquam maximus eros vel tempor rutrum."
        +"Proin ultrices sem tellus, non facilisis purus congue sit amet. Suspendisse venenatis orci at enim dictum commodo. Curabitur placerat tincidunt lacus, et semper ipsum sagittis ac. Duis id enim accumsan, condimentum erat et, auctor nunc. Etiam orci nisl, viverra at purus vulputate, fermentum efficitur massa. Nunc urna quam, porta porta bibendum id, aliquam nec magna. Aenean lobortis ipsum porttitor lacus ullamcorper ornare. Suspendisse justo diam, ultricies eu sem non, porttitor venenatis turpis."
        +"Cras vulputate, tellus ac facilisis sagittis, ligula felis consequat neque, sed pharetra purus dui ac felis. Fusce sed tortor sapien. Morbi sem nisl, sagittis ut ante quis, maximus placerat neque. Donec nec eleifend nunc, in consequat ex. Nunc commodo leo malesuada mi faucibus, sodales maximus lorem tincidunt. Nulla non mollis magna. Sed eu massa vel orci sollicitudin tempor quis nec tellus. Quisque id ullamcorper sem. Aenean eu felis non leo lobortis hendrerit. Integer volutpat feugiat lacus. Sed tempor, leo suscipit varius fringilla, dui sem convallis lorem, non elementum lacus ex sed odio. Aenean at quam lobortis, ullamcorper enim a, posuere turpis. Sed bibendum lacus vel magna mollis, nec rutrum erat aliquet."
        +"Praesent in magna dolor. Suspendisse sed ultricies orci, id porta mi. Pellentesque varius, nibh in gravida sagittis, turpis justo congue dolor, nec pellentesque lectus orci vel odio. Donec tortor justo, tempus in metus nec, ullamcorper tempor erat. Suspendisse aliquet sed sapien nec sagittis. Duis ut efficitur mauris, vel cursus libero. Maecenas et luctus dolor, et condimentum urna. Phasellus sit amet orci pretium, consectetur tortor ut, tempus lorem. Mauris vel dolor massa. Nulla lobortis, sapien a rhoncus sodales, nisi diam vulputate mi, id vehicula mauris sem sit amet massa. Cras fermentum, nibh sed rutrum mattis, turpis erat commodo sem, nec molestie felis ligula at sapien. Quisque pellentesque at nisl vitae blandit. Nulla facilisi."
        +"Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Maecenas efficitur vel est quis cursus. Aenean lacinia tortor lobortis eros interdum, quis gravida nisi semper. Cras mauris nisi, blandit sit amet magna eget, porta ultricies sapien. Nunc ante nibh, semper sed nunc sit amet, congue eleifend augue. Sed hendrerit quis sem a dignissim. Duis sed est venenatis, laoreet odio at, aliquet nibh. Cras neque nibh, porttitor in feugiat posuere, tempus a leo. Cras gravida commodo orci, a interdum sapien dictum at. Maecenas porttitor ex non nibh porttitor, vel fringilla augue interdum. Duis sit amet justo diam. Praesent malesuada commodo imperdiet. Nam at nulla rutrum, ornare tellus vitae, accumsan tortor. Sed pharetra justo sit amet bibendum volutpat. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos."
    }
}
